sportnews/forum/urls.py
from django.urls import path
from .views import *


app_name = 'forum'

urlpatterns = [
    path('', main_forum, name='all_treads'),
    path('<int:main_tread_id>/', treads_from_main, name='detail_main'),
    path('<int:main_tread_id>/<int:tread_id>', tread_detail, name='one_tread'),
    path('<int:main_tread_id>/delete/<int:tread_id>', delete_tread, name='delete_tread')
]

sportnews/main/urls.py
from django.urls import path
from .views import *


app_name = 'main'

urlpatterns = [
    path('', AllNews.as_view(), name='all_news'),
    path('category/<int:genre_id>/', CategoryNews.as_view(), name='genre_news'),
    path('<int:news_id>/', view_news, name='detail'),
    path('register/', register, name='register'),
    path('login/', user_login, name='login'),
    path('logout/', user_logout, name='logout'),
    path('add-news/', CreateNews.as_view(), name='add_news'),
]

sportnews/sportnews/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('news/', include('main.urls')),
    path('forum/', include('forum.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
                    path('__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns
    
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sportnews/templates/inc/_nav.html
{% load news_tags %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-xxl">
      <a class="navbar-brand" href="{% url 'main:all_news' %}">SportNews</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          {% get_genre as genre %}
          <li class="nav-item"><a class="nav-link" href="{% url 'main:all_news' %}">Главная</a></li>
          {% for item in genre %}
          <li class="nav-item"><a class="nav-link" href="{{ item.get_absolute_url }}">{{ item.name }}</a></li>
          {% endfor %}
          <li class="nav-item"><a class="nav-link" href="{% url 'forum:all_treads' %}">Форум</a></li>
        </ul>
        {% if perms.news.add_news %}
          <p class="navbar-text" style="margin-right: 10px;"><a href="{% url 'main:add_news' %}">Добавить новость</a></p>
        {% endif %}
        <span class="navbar-text">
          {% if request.user.is_authenticated %}
          <p>Привет, {{ user.username }}!!! | <a href="{% url 'main:logout' %}">Выход</a></p>
          {% else %}
          <a href="{% url 'main:register' %}">Регистрация</a> | <a href="{% url 'main:login' %}">Войти</a>
          {% endif %}
        </span>
      </div>
    </div>
  </nav>

sportnews/templates/inc/_sidebar.html
{% load news_tags %}
<div class="list-group list-group-flush">
        <h6 style="margin-bottom: 5px; padding-top: 5px;">&#128293;Горячие новости:</h6>
        {% get_news as news %}
        {% for item in news %}
                <a href="{{ item.get_absolute_url }}" class="list-group-item list-group-item-action">
                    <span style="font-size: 13px;">{{ item.title }}</span><br>
                    <span style="font-size: 12px;">&#128065; {{ item.views }}</span>
                </a>
    {% endfor %}
</div>