sportnews/forum/urls.py
from django.urls import path
from .views import *


app_name = 'forum'

urlpatterns = [
    path('', main_forum, name='all_treads'),
    path('<int:main_tread_id>/', treads_from_main, name='detail_main'),
    path('<int:main_tread_id>/<int:tread_id>', tread_detail, name='one_tread'),
    path('<int:main_tread_id>/delete/<int:tread_id>', delete_tread, name='delete_tread')
]

sportnews/main/urls.py
from django.urls import path
from .views import *


app_name = 'main'

urlpatterns = [
    path('', AllNews.as_view(), name='all_news'),
    path('category/<int:genre_id>/', CategoryNews.as_view(), name='genre_news'),
    path('<int:news_id>/', view_news, name='detail'),
    path('register/', register, name='register'),
    path('login/', user_login, name='login'),
    path('logout/', user_logout, name='logout'),
    path('add-news/', CreateNews.as_view(), name='add_news'),
]

sportnews/sportnews/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('news/', include('main.urls')),
    path('forum/', include('forum.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
                    path('__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns
    
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sportnews/forum/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


class Category(models.Model):
    title = models.CharField(max_length=255)
    date_create = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


class MainTreads(models.Model):
    title = models.CharField(max_length=255)
    discription = models.TextField()
    date_create = models.DateTimeField(auto_now_add=True)
    date_update = models.DateTimeField(auto_now=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=False, blank=False)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Главный тред"
        verbose_name_plural = "Главные треды"
        ordering = ['-date_create']

    def get_absolute_url(self):
        return reverse('forum:detail_main', kwargs={"main_tread_id": self.pk})


class Treads(models.Model):
    title = models.CharField(max_length=255)
    discription = models.TextField()
    date_create = models.DateTimeField(auto_now_add=True)
    date_update = models.DateTimeField(auto_now=True)
    main_treads = models.ForeignKey(MainTreads, related_name='treads', on_delete=models.CASCADE, null=False, blank=False)
    user_id = models.ForeignKey(User, on_delete=models.CASCADE, null=False, blank=False)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Тред"
        verbose_name_plural = "Треды"
        ordering = ['-date_create']

    def get_absolute_url(self):
        return reverse('forum:one_tread', kwargs={"tread_id": self.pk, "main_tread_id": self.main_treads.pk})


class Comments(models.Model):
    user_id = models.ForeignKey(User, related_name='user_treads', on_delete=models.CASCADE, null=True, blank=True)
    treads = models.ForeignKey(Treads, related_name='comments_treads', on_delete=models.CASCADE, null=False, blank=False)
    comment_text = models.TextField()
    date_create = models.DateTimeField(auto_now_add=True)
    date_update = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'Comment by {self.user_id} on {self.treads}'

sportnews/forum/forms.py
from django import forms
from .models import Comments, Treads
import re
from django.core.exceptions import ValidationError



class CommentForm(forms.ModelForm):
    class Meta:
        model = Comments
        fields = ['comment_text']
        widgets = {
            'comment_text': forms.Textarea(attrs={
                'class': 'form-control',
                'rows': 5,
            }),
        }

class TreadsForm(forms.ModelForm):
    class Meta:
        model = Treads
        # fields = '__all__'
        fields = ['title', 'discription']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'discription': forms.Textarea(attrs={
                'class': 'form-control',
                'rows': 5,
            }),
        }
    
    def clean_title(self):
        title = self.cleaned_data['title']
        if re.match(r'\d', title):
            raise ValidationError('Название не должно начинаться с цифры')
        return title

sportnews/forum/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import *
from .forms import CommentForm, TreadsForm
from django.http import HttpResponseRedirect
from django.urls import reverse

def main_forum(request):
    main_category = Category.objects.all()
    main_treads = MainTreads.objects.all()
    for mtread in main_treads:
        comments_count = 0
        for tread in mtread.treads.all():
            comments_count += len(tread.comments_treads.all())
        mtread.comments_count = comments_count

    return render(request, 'forum/forum.html', {
        'main_category': main_category,
        'main_treads': main_treads
    })

def treads_from_main(request, main_tread_id):
    treads_list = Treads.objects.filter(main_treads=main_tread_id)
    main_tread = MainTreads.objects.get(pk=main_tread_id)

    if request.method == 'POST':
        tread_form = TreadsForm(data=request.POST)
        if tread_form.is_valid():
            new_tread = tread_form.save(commit=False)
            new_tread.main_treads, new_tread.user_id = main_tread, request.user
            new_tread.save()
            return redirect(new_tread)
    
    else:
        tread_form = TreadsForm()

    return render(request, 'forum/detail_main_tread.html', {
        'treads_list': treads_list,
        'main_tread': main_tread,
        'tread_form': tread_form,
    })

def tread_detail(request, main_tread_id, tread_id):
    tread = Treads.objects.get(pk=tread_id)

    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.treads, new_comment.user_id = tread, request.user
            new_comment.save()
            return redirect(request.path)
    else:
        comment_form = CommentForm()

    return render(request, 'forum/detail_tread.html', {
        'tread': tread,
        'comment_form': comment_form
    })


def delete_tread(request, main_tread_id, tread_id):
    delete_tread = Treads.objects.get(pk=tread_id)
    delete_tread.delete()
    return redirect(reverse('forum:detail_main', kwargs={"main_tread_id": main_tread_id}))

sportnews/main/views.py
from django.shortcuts import render, redirect, get_object_or_404, get_list_or_404
from django.http import HttpResponse
from .models import News, Genre
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.views.generic import ListView, DetailView, CreateView
from .forms import UserRegisterForm, UserLoginForm, NewsForm, CommentForm
from django.contrib.auth import login, logout
from django.contrib import messages


class AllNews(ListView):
    model = News
    template_name = 'main/index.html'
    context_object_name = 'news_list'
    allow_empty = False
    paginate_by = 10
    # extra_context = {'title': 'Главная'}

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            context['main_news'] = [context['news_list'][item] for item in range(0, 2)]
        except IndexError:
            context['main_news'] = None
        try:
            context['sub_news'] = [context['news_list'][item] for item in range(2, 5)]
        except IndexError:
            context['sub_news'] = None
        return context

    def get_queryset(self):
        return News.objects.all()


class CategoryNews(ListView):
    model = News
    template_name = 'main/genre_news.html'
    context_object_name = 'news_list'
    allow_empty = False
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = Genre.objects.get(pk=self.kwargs['genre_id'])
        context['one_main_news'] = context['news_list'][0]
        context['other_news'] = [context['news_list'][item] for item in range(1, len(context['news_list']))]
        return context

    def get_queryset(self):
        return News.objects.filter(genre_id=self.kwargs['genre_id']).select_related('genre')


# class DetailNews(DetailView):
#     model = News
#     context_object_name = 'one_news'
#     # template_name = 'news/news_detail.html'
#     # pk_url_kwarg = 'news_id'

def view_news(request, news_id):
    # news_item = News.objects.get(pk=news_id)
    news_item = get_object_or_404(News, pk=news_id)
    news_item.views += 1
    news_item.save()
    comments = news_item.comments.all()

    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.news, new_comment.name, new_comment.email = news_item, request.user.username, request.user.email
            new_comment.save()
            return redirect(f'news/{news_id}')
    else:
        comment_form = CommentForm()

    return render(request, 'main/news_detail.html', {
        'one_news': news_item,
        'comments': comments,
        'comment_form': comment_form
    })


class CreateNews(LoginRequiredMixin, CreateView):
    form_class = NewsForm
    template_name = 'main/add_news.html'
    login_url = '/admin/'


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, 'Регистрация успешна')
            return redirect('/news')
        else:
            messages.error(request, 'Ошибка регистрации')
    else:
        form = UserRegisterForm()
    return render(request, 'main/register.html', {'form': form})


def user_login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('/news')
    else:
        form = UserLoginForm()
    return render(request, 'main/login.html', {'form': form})


def user_logout(request):
    logout(request)
    return redirect('/news/login')

sportnews/forum/templates/forum/detail_main_tread.html
{% extends 'forum_base.html' %}
{% load plur %}
{% block forum %}
	<div class="container" style="margin-top: 10px;">
        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLabel">Добавить топик</h5>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="container">
                    <form action="{{ main_tread.main_tread_id }}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        
                        <div class="form-group">
                            <label for="{{ tread_form.title.id_for_label }}" class="form-label">Название: </label>
                            {{ tread_form.title }}
                            <div class='invalid-feedback'>
                                {{ tread_form.title.errors }}
                            </div>
                        </div>
                    
                        <div class="form-group">
                            <label for="{{ tread_form.discription.id_for_label }}" class="form-label">Текст: </label>
                            {{ tread_form.discription }}
                            <div class='invalid-feedback'>
                                {{ tread_form.discription.errors }}
                            </div>
                        </div>

                        <br>
      
                        <button type="submit" class="btn btn-primary btn-block">Добавить</button>
                    </form>
                    </div>
                </div>
              </div>
            </div>
          </div>
		<div class="row justify-content-center">
			<div class="col-10">
                <div class="row justify-content-between" style="padding-bottom: 1%;">
                    <div class="col-7">
                        <span class="fw-bold">{{ main_tread.discription }}</span>
                    </div>
                    <div class="col-3" style="width: 100px; height: 10px;">
                        {% if user.is_authenticated %}
                        <button type="button" class="btn btn-dark" data-bs-toggle="modal" data-bs-target="#exampleModal">
                            Добавить
                        </button>
                        {% endif %}
                    </div>
                </div>
				{% for tread in treads_list %}
                <div class="row align-items-center">
                    <div class="col-11">
                        <ol class="list-group list-group-flush" style="padding-top: 10px;">
                            <a class="list-group-item list-group-item-action d-flex justify-content-between align-items-start" href="{{ tread.get_absolute_url }}">
                                <div style="height: 50px; width: 50px;">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" fill="currentColor" class="bi bi-chat-left-dots" viewBox="0 0 20 20">
                                        <path d="M14 1a1 1 0 0 1 1 1v8a1 1 0 0 1-1 1H4.414A2 2 0 0 0 3 11.586l-2 2V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12.793a.5.5 0 0 0 .854.353l2.853-2.853A1 1 0 0 1 4.414 12H14a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
                                        <path d="M5 6a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm4 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm4 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0z"/>
                                    </svg>
                                </div>
                                <div class="ms-2 me-auto" style="margin-left: 10px">
                                    <span class="text-break">{{ tread.title }}</span>
                                </div>
                                <span class="badge bg-light rounded-pill text-dark" style="margin-left: 10px;">{{ tread.comments_treads.count }} {{ tread.comments_treads.count|ru_plural:"сообщение,сообщения,сообщений" }}</span>
                            </a>
                        </ol>
                    </div>
                    {% if perms.forum.delete_treads %}
                        <div class="col-1">
                            <a href="delete/{{ tread.id }}">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash3" viewBox="0 0 20 20">
                                    <path d="M6.5 1h3a.5.5 0 0 1 .5.5v1H6v-1a.5.5 0 0 1 .5-.5ZM11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3A1.5 1.5 0 0 0 5 1.5v1H2.506a.58.58 0 0 0-.01 0H1.5a.5.5 0 0 0 0 1h.538l.853 10.66A2 2 0 0 0 4.885 16h6.23a2 2 0 0 0 1.994-1.84l.853-10.66h.538a.5.5 0 0 0 0-1h-.995a.59.59 0 0 0-.01 0H11Zm1.958 1-.846 10.58a1 1 0 0 1-.997.92h-6.23a1 1 0 0 1-.997-.92L3.042 3.5h9.916Zm-7.487 1a.5.5 0 0 1 .528.47l.5 8.5a.5.5 0 0 1-.998.06L5 5.03a.5.5 0 0 1 .47-.53Zm5.058 0a.5.5 0 0 1 .47.53l-.5 8.5a.5.5 0 1 1-.998-.06l.5-8.5a.5.5 0 0 1 .528-.47ZM8 4.5a.5.5 0 0 1 .5.5v8.5a.5.5 0 0 1-1 0V5a.5.5 0 0 1 .5-.5Z"/>
                                </svg>
                            </a>
                        </div>
                    {% endif %}
                </div>
				{% endfor %}
			</div>
		</div>
	</div>

{% endblock %}

sportnews/forum/templates/forum/detail_tread.html
{% extends 'forum_base.html' %}
{% block forum %}
    <div class="container" style="margin-top: 10px;">
        <div class="row justify-content-center">
            <div class="col-10">
                <h5 class="card-title">{{ tread.title }}</h5>
                <div class="card" style="width: 60rem;">
                    <div class="card-body">
                        <div class="row justify-content-between">
                            <div class="col-8">
                                <h5 class="card-title">{{ tread.user_id.username }}</h5>
                            </div>
                            <div class="col-2">
                                <h6 class="card-subtitle mb-2 text-muted">{{ tread.date_create|date:"d.m.Y H:i" }}</h6>
                            </div>
                        </div>
                        <p class="card-text">{{ tread.discription|linebreaks }}</p>
                    </div>
                </div>
                <hr style="width: 60rem;">
                <div style="margin-top: 15px;">
                    {% for comment in tread.comments_treads.all %}
                        <div class="comment" style="margin-top: 5px;">
                            <div class="card" style="width: 60rem;">
                                <div class="card-body">
                                    <div class="row justify-content-between">
                                        <div class="col-8">
                                            <h5 class="card-title">{{ comment.user_id.username }}</h5>
                                        </div>
                                        <div class="col-2">
                                            <h6 class="card-subtitle mb-2 text-muted">{{ comment.date_create|date:"d.m.Y H:i" }}</h6>
                                        </div>
                                    </div>
                                            <p class="card-text">{{ comment.comment_text|linebreaks }}</p>
                                </div>
                            </div>
                        </div>
                    {% empty %}
                        <p>Ещё никто не оставил комментарий. Будь первым!</p>
                    {% endfor %}
                </div>
                <div style="margin-top: 20px;">
                    {% if new_comment %}
                        <h5>Ваш комментарий добавлен</h5>
                    {% else %}
                        <h5>Добавить комментарий:</h5>
                        <form action="{{ tread.tread_id }}" method="post">
                        {% csrf_token %}
                        {% if user.is_authenticated %}
                            <div class="form-group">
                                {{ comment_form.comment_text }}
                                <div class='invalid-feedback'>
                                    {{ comment_form.comment_text.errors }}
                                </div>
                            </div>
                        <button type="submit" class="btn btn-primary btn-block" style="margin-top: 10px;">Добавить комментарий</button>
                        </form>
                        {% else %}
                            <p>Комментирование доступно только зарегистрированным пользователям</p>
                        {% endif %}
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

sportnews/forum/templates/forum/forum.html
{% extends 'forum_base.html' %}
{% load plur %}
{% block forum %}
	<div class="container" style="margin-top: 10px;">
		<div class="row justify-content-center">
			<div class="col-10">
				{% for item in main_category %}
					<span class="fw-bold">{{ item.title }}</span>
					<ol class="list-group list-group-flush" style="margin-top: 10px;">
						{% for mtread in main_treads %}
							{% if mtread.category.title == item.title %}
								<a class="list-group-item list-group-item-action d-flex justify-content-between align-items-start" href="{{ mtread.get_absolute_url }}">
									<div style="height: 50px; width: 50px;">
										<svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" fill="currentColor" class="bi bi-chat-left-dots" viewBox="0 0 20 20">
											<path d="M14 1a1 1 0 0 1 1 1v8a1 1 0 0 1-1 1H4.414A2 2 0 0 0 3 11.586l-2 2V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12.793a.5.5 0 0 0 .854.353l2.853-2.853A1 1 0 0 1 4.414 12H14a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
											<path d="M5 6a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm4 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm4 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0z"/>
										</svg>
									</div>
									<div class="ms-2 me-auto" style="margin-left: 10px">
										<span class="text-break">{{ mtread.title }}</span>
									</div>
									<span class="badge bg-light rounded-pill text-dark" style="margin-left: 10px;">{{ mtread.treads.count }} тем | {{ mtread.comments_count }} {{ mtread.comments_count|ru_plural:"сообщение,сообщения,сообщений" }}</span>
								</a>
							{% endif %}
						{% endfor %}
					</ol>
				{% endfor %}
			</div>
		</div>
	</div>

{% endblock %}